pathToCSV: "avengers/print-t.csv"
firstCellToIgnore: "Card Name"
villain: 'Villain'
villainPath: 'villainframe.png'
hero: 'Hero'
heroPath: 'heroframe.png'
superpower: 'Super Power'
superpowerPath: 'spframe.png'
equipment: 'Equipment'
equipmentPath: 'eqframe.png'
location: 'Location'
locationPath: 'locframe.png'
supervillain: 'Super Villain'
supervillainPath: 'supervillain.png'
superlocation: 'Super Location'
superequipment: 'Super Equipment'
imagepath: 'images/'
rowsToPrint: 74
#rowsToPrint: 3
startPrintLine: 2
range: True
cardsToPrint:
  - 30
  - 31
  - 32
  - 33
  - 8
  - 61
  - 65
  - 4
  - 46
  - 47
  - 23
  - 28
  - 11
  - 60
  - 41
  - 37
  - 63
