pathToCSV: "data/IASIPGAME.csv"
firstCellToIgnore: "CARD NAME"
villain: 'TRASHY'
villainPath: 'sunnytrash.png'
hero: 'CLASSY'
heroPath: 'sunnyclass.png'
superpower: 'SPECIAL'
superpowerPath: 'sunnyspecial.png'
equipment: 'EQUIPMENT'
equipmentPath: 'sunnyeq.png'
location: 'LOCATION'
locationPath: 'sunnyloc.png'
supervillain: 'ENEMY'
supervillainPath: 'enemy.png'
superlocation: 'none'
superequipment: 'none'
imagepath: 'IASIP/'
rowsToPrint: 69

